name: Linux CI

on:
  schedule:
    - cron: "0 6 * * *"
  push:
  pull_request:

jobs:
  ci-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    name: Linux CI
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python environment report
        run: python -c "import sys; print(sys.version)"
      - name: Run ${{ matrix.python-version }} test (single font, default)
        uses: f-actions/hyperglot@main
        with:
          path: "tests/fonts/Roboto-Regular.ttf"
      - name: Run ${{ matrix.python-version }} test (globbed fonts, default)
        uses: f-actions/hyperglot@main
        with:
          path: "tests/fonts/*.ttf"
